---
# NOTE keycloak object must be in the operator's namespace
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  instances: 1
  db:
    vendor: {{ .Values.keycloak.database.vendor }}
    host: {{ .Values.keycloak.database.host }}
    usernameSecret:
      name: db-secret
      key: username
    passwordSecret:
      name: db-secret
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
  ingress:
    enabled: false
