---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  instances: 1
  hostname: INSECURE-DISABLE
  tlsSecret: INSECURE-DISABLE
  disableDefaultIngress: true
