---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakClient
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: devops-stack-applications
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "devops-stack-module-keycloak.selector" $ | indent 6 }}
  client:
    clientId: {{ .Values.keycloak.keycloakClient.client.clientId }}
    secret: {{ .Values.keycloak.keycloakClient.client.secret }}
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    redirectUris:
      {{- toYaml .Values.keycloak.keycloakClient.client.redirectUris | nindent 6 }}
    defaultClientScopes:
      - "email"
      - "profile"
