---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealm
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: devops-stack
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  realm:
    id: devops-stack
    realm: devops-stack
    enabled: true
    displayName: DevOps Stack Realm
  instanceSelector:
    matchLabels:
      {{- include "devops-stack-module-keycloak.selector" $ | indent 6 }}
