{{- range $username, $infos := .Values.keycloak.keycloakUsers }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakUser
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ $username }}
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  user:
    username: {{ $username }}
    firstName: {{ $infos.first_name }}
    lastName: {{ $infos.name }}
    email: {{ $infos.email | quote }}
    enabled: true
    emailVerified: true
    credentials:
      - temporary: false
        type: password
        value: {{ $infos.password | quote }}
    clientRoles:
      account:
        - manage-account
  realmSelector:
    matchLabels:
      {{- include "devops-stack-module-keycloak.selector" $ | indent 6 }}
{{- end }}
