---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak-realm-devops-stack
  labels:
    {{- include "devops-stack-module-keycloak.labels" $ | indent 4 }}
spec:
  keycloakCRName: keycloak # Name of the CR that created the Keycloak
  
  # Realm definition (user definition and authentication settings must be inside)  
  realm:
    enabled: true
    realm: devops-stack
    id: devops-stack
    displayName: DevOps Stack Realm

    # OIDC client configuration
    clients:
    - id: devops-stack-applications
      enabled: true
      clientId: {{ .Values.keycloak.keycloakClient.client.clientId }}
      secret: {{ .Values.keycloak.keycloakClient.client.secret }}
      clientAuthenticatorType: client-secret
      standardFlowEnabled: true
      defaultClientScopes:
      - "email"
      - "profile"
      redirectUris:
        {{- toYaml .Values.keycloak.keycloakClient.client.redirectUris | nindent 8 }}

    # OIDC user definitions
    users:
    {{- range $username, $infos := .Values.keycloak.keycloakUsers }}
    - username: {{ $username }}
      firstName: {{ $infos.first_name }}
      lastName: {{ $infos.name }}
      email: {{ $infos.email | quote }}
      enabled: true
      emailVerified: true
      credentials:
      - temporary: false
        type: password
        value: {{ $infos.password | quote }}
      clientRoles:
        account:
        - manage-account
    {{- end }}
